### ISSUE TITLE
CAN NOT download from URL

### ISSUE THREAD

**Issue by VictoryLoveJessica** [PinataFarms/DAD-3DHeads#3]
Thanks for your great work!
But I met this problem when I compiled the demo.py：

Traceback (most recent call last):
  File "demo.py", line 60, in <module>
    Fire(demo)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "demo.py", line 48, in demo
    predictor = FaceMeshPredictor.dad_3dnet()
  File "/cto_studio/vistring/zhangtianke_code/DAD-3DHeads/predictor.py", line 179, in dad_3dnet
    download_model()
  File "/cto_studio/vistring/zhangtianke_code/DAD-3DHeads/predictor.py", line 33, in download_model
    os.path.join(os.path.expanduser("~"), ".dad_checkpoints", _FILENAME)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/zhangtianke/anaconda3/envs/DAD-3DHeads/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

I can not visit the "https://media.pinatafarm.com/public/research/dad-3dheads/dad_3dheads.trcd" 
Can you give me some files?

**Comment by burnmyletters** [comment]
Hello,

please try this [link](https://drive.google.com/file/d/1ZZ9Ct3DR_zYMFBZSRUKiCf_x8Dt3otRk/view?usp=sharing)

**Comment by VictoryLoveJessica** [comment]
Thx a lot!
